sudo: required
services:
    - docker

before_install:
    - docker build -t theob69/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true theob69/docker-react npm run test -- --coverage